name: GitHub TestNG Suite
run-name: ${{github.actor}} is testing TestNG Script
on: [push]
jobs:
  explore-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: check out repository code
        uses: actions/checkout@v4
      - name: Runs Maven command
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: build with maven and run TestNGSuite
        run: mvn clean test 
